import { ReelData } from './types';

export const reelsData: ReelData[] = [
    {
        id: '1',
        user: {
            id: 'user1',
            name: 'أحمد محمد',
            username: 'ahmed_m',
            avatar: 'https://i.pravatar.cc/150?img=12',
            verified: true,
            followers: 125000,
            isFollowing: false,
        },
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        thumbnail: 'https://picsum.photos/400/800?random=1',
        duration: 30,
        likes: 45200,
        views: 1250000,
        comments: 3420,
        shares: 890,
        liked: false,
        saved: false,
        muted: false,
        description: 'هدف رائع في الدقيقة الأخيرة! 🔥⚽',
        hashtags: ['كرة_القدم', 'أهداف', 'الدوري_المصري'],
        location: 'القاهرة، مصر',
        createdAt: new Date('2024-01-15'),
    },
    {
        id: '2',
        user: {
            id: 'user2',
            name: 'سارة علي',
            username: 'sara_ali',
            avatar: 'https://i.pravatar.cc/150?img=25',
            verified: false,
            followers: 8500,
            isFollowing: true,
        },
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        thumbnail: 'https://picsum.photos/400/800?random=2',
        duration: 25,
        likes: 12300,
        views: 450000,
        comments: 890,
        shares: 234,
        liked: true,
        saved: false,
        muted: false,
        description: 'تحليل تكتيكي للمباراة 📊',
        hashtags: ['تحليل', 'كرة_القدم'],
        location: 'الإسكندرية، مصر',
        createdAt: new Date('2024-01-14'),
    },
    {
        id: '3',
        user: {
            id: 'user3',
            name: 'محمد حسن',
            username: 'mohamed_h',
            avatar: 'https://i.pravatar.cc/150?img=33',
            verified: true,
            followers: 250000,
            isFollowing: false,
        },
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        thumbnail: 'https://picsum.photos/400/800?random=3',
        duration: 45,
        likes: 67800,
        views: 2100000,
        comments: 5670,
        shares: 1450,
        liked: false,
        saved: true,
        muted: false,
        description: 'أفضل اللحظات من المباراة! ⚡',
        hashtags: ['مباراة', 'أهداف', 'مهارات'],
        location: 'الجيزة، مصر',
        createdAt: new Date('2024-01-13'),
    },
];
