-- AlterTable: Add new fields to AuditLog
ALTER TABLE "audit_logs" 
  ALTER COLUMN "actorId" DROP NOT NULL,
  ALTER COLUMN "targetId" DROP NOT NULL,
  ALTER COLUMN "targetType" DROP NOT NULL,
  ADD COLUMN "resource" TEXT NOT NULL DEFAULT 'UNKNOWN',
  ADD COLUMN "ip" TEXT,
  ADD COLUMN "userAgent" TEXT;

-- CreateIndex: Add index on resource field
CREATE INDEX "audit_logs_resource_idx" ON "audit_logs"("resource");

-- AlterEnum: Add new audit actions
ALTER TYPE "AuditAction" ADD VALUE 'LOGIN';
ALTER TYPE "AuditAction" ADD VALUE 'LOGOUT';
ALTER TYPE "AuditAction" ADD VALUE 'LOGIN_FAILED';
ALTER TYPE "AuditAction" ADD VALUE 'TOKEN_REFRESH';
ALTER TYPE "AuditAction" ADD VALUE 'PASSWORD_RESET';
ALTER TYPE "AuditAction" ADD VALUE 'ACCOUNT_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'ACCOUNT_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'ACCOUNT_DELETION_INITIATED';
ALTER TYPE "AuditAction" ADD VALUE 'ACCOUNT_DELETION_CANCELLED';
ALTER TYPE "AuditAction" ADD VALUE 'ACCOUNT_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_UNBANNED';
ALTER TYPE "AuditAction" ADD VALUE 'RATE_LIMIT_EXCEEDED';
ALTER TYPE "AuditAction" ADD VALUE 'UNAUTHORIZED_ACCESS';
ALTER TYPE "AuditAction" ADD VALUE 'SUSPICIOUS_ACTIVITY';

-- AlterEnum: Add new audit target type
ALTER TYPE "AuditTargetType" ADD VALUE 'ACCOUNT';
