import { randomBytes } from 'crypto';
import { clerkClient } from '@clerk/express';
import prisma from '../lib/prisma';
import { logger } from '../utils/logger';
import { awardDailyLogin } from './xp.service';
import { sanitizeTimezone } from '../utils/chat-timezone';
import { generateUsername } from '../utils/username.utils';

function isClerkOAuthUser(clerkUser: {
    externalAccounts?: unknown[];
    passwordEnabled?: boolean;
}): boolean {
    if (Array.isArray(clerkUser.externalAccounts) && clerkUser.externalAccounts.length > 0) {
        return true;
    }
    return clerkUser.passwordEnabled === false;
}

function buildDisplayNameFromClerk(
    clerkUser: {
        firstName?: string | null;
        lastName?: string | null;
        externalAccounts?: Array<{
            firstName?: string | null;
            lastName?: string | null;
            provider?: string;
        }>;
    },
    email?: string,
): string {
    const fromName = `${clerkUser.firstName || ''} ${clerkUser.lastName || ''}`.trim();
    if (fromName) return fromName;

    const accounts = clerkUser.externalAccounts || [];
    for (const account of accounts) {
        const fromExternal = `${account.firstName || ''} ${account.lastName || ''}`.trim();
        if (fromExternal) return fromExternal;
    }

    const local = email?.split('@')[0]?.replace(/[._-]+/g, ' ').trim();
    if (local) return local;

    return '';
}

function isAutoGeneratedProfile(user: { username: string; displayName?: string | null }): boolean {
    const displayName = (user.displayName || '').trim();
    if (!displayName) return true;
    if (displayName === user.username) return true;
    if (/^user_[a-z0-9]+$/i.test(displayName)) return true;
    return false;
}

// ✅ Cache for Clerk API responses (5 minutes TTL)
const clerkUserCache = new Map<string, { data: any; timestamp: number }>();
const CLERK_CACHE_TTL = 5 * 60 * 1000; // 5 minutes

// ✅ OPTIMIZED: Timeout wrapper with retry for Clerk API calls
const clerkApiWithTimeout = async <T>(
    apiCall: () => Promise<T>,
    timeoutMs: number = 8000, // ✅ Reduced to 8 seconds
    retries: number = 2 // ✅ Added retry logic
): Promise<T> => {
    let lastError: Error | null = null;
    
    for (let attempt = 0; attempt < retries; attempt++) {
        try {
            return await Promise.race([
                apiCall(),
                new Promise<T>((_, reject) =>
                    setTimeout(() => reject(new Error('Clerk API timeout')), timeoutMs)
                ),
            ]);
        } catch (error: any) {
            lastError = error;
            if (attempt < retries - 1) {
                logger.warn(`[Clerk API] Retry ${attempt + 1}/${retries - 1}...`);
                await new Promise(resolve => setTimeout(resolve, 500)); // 500ms delay
            }
        }
    }
    
    throw lastError || new Error('Clerk API failed after retries');
};

async function fetchClerkUserCached(clerkUserId: string): Promise<any> {
    const cached = clerkUserCache.get(clerkUserId);
    if (cached && Date.now() - cached.timestamp < CLERK_CACHE_TTL) {
        return cached.data;
    }

    const clerkUser = await clerkApiWithTimeout(
        () => clerkClient.users.getUser(clerkUserId),
        8000,
        2,
    );
    clerkUserCache.set(clerkUserId, { data: clerkUser, timestamp: Date.now() });
    return clerkUser;
}

export class ClerkUserService {
    /**
     * If the DB row still has an auto-generated name, pull Google/Apple name from Clerk.
     */
    private static async refreshAutoProfileFromClerk(
        user: { id: string; username: string; displayName?: string | null; avatar?: string | null },
        clerkUserId: string,
    ) {
        if (!isAutoGeneratedProfile(user)) return null;

        try {
            const clerkUser = await fetchClerkUserCached(clerkUserId);
            const addresses = clerkUser.emailAddresses || [];
            let primaryEmail = addresses.find(
                (email: { id: string }) => email.id === clerkUser.primaryEmailAddressId,
            );
            if (!primaryEmail && addresses.length > 0) {
                primaryEmail = addresses[0];
            }
            const emailAddr = primaryEmail?.emailAddress as string | undefined;
            const displayName = buildDisplayNameFromClerk(clerkUser, emailAddr);

            const updateData: {
                displayName?: string;
                avatar?: string;
            } = {};

            if (displayName && displayName !== user.displayName) {
                updateData.displayName = displayName;
            }

            const clerkAvatar = clerkUser.imageUrl as string | undefined;
            if (
                clerkAvatar &&
                (!user.avatar || user.avatar.includes('clerk.com'))
            ) {
                updateData.avatar = clerkAvatar;
            }

            if (!Object.keys(updateData).length) return null;

            return await prisma.user.update({
                where: { id: user.id },
                data: updateData,
            });
        } catch (err) {
            logger.warn(`[findOrCreateUser] ⚠️ Could not refresh profile from Clerk:`, err);
            return null;
        }
    }
    /**
     * Create a DB user when Clerk is down or the account has no usable email yet.
     * Uses deterministic email/username from clerkUserId so retries stay idempotent.
     */
    private static async createMinimalClerkUser(clerkUserId: string) {
        const minimalEmail = `${clerkUserId}@clerk.temp`;
        const baseUser = `user_${clerkUserId.replace(/[^a-zA-Z0-9_]/g, '').slice(-12) || clerkUserId.slice(-8)}`;

        const tryCreate = async (username: string) => {
            return prisma.user.create({
                data: {
                    clerkUserId,
                    email: minimalEmail,
                    username,
                    displayName: username,
                    emailVerified: false,
                    coins: 50,
                    level: 1,
                    xp: 0,
                },
            });
        };

        try {
            const user = await tryCreate(baseUser);
            logger.info(`[createMinimalClerkUser] ✅ Minimal user created: ${user.username}`);
            return user;
        } catch (createError: any) {
            if (createError.code === 'P2002') {
                const byClerk = await prisma.user.findUnique({ where: { clerkUserId } });
                if (byClerk) return byClerk;
                const byEmail = await prisma.user.findUnique({ where: { email: minimalEmail } });
                if (byEmail) return byEmail;
                // Rare: username unique clash with another row — retry with random suffix
                const altUsername = `${baseUser}_${randomBytes(3).toString('hex')}`;
                try {
                    const user = await tryCreate(altUsername);
                    logger.info(`[createMinimalClerkUser] ✅ Minimal user created (alt username): ${user.username}`);
                    return user;
                } catch (e2: any) {
                    if (e2.code === 'P2002') {
                        const again = await prisma.user.findUnique({ where: { clerkUserId } });
                        if (again) return again;
                    }
                    throw e2;
                }
            }
            throw createError;
        }
    }

    /**
     * Find or create user from Clerk ID
     * This syncs Clerk user data with our database
     * ✅ OPTIMIZED: Added caching and timeout for Clerk API
     */
    static async findOrCreateUser(clerkUserId: string) {
        try {
            logger.info(`[findOrCreateUser] 🔍 Looking for user: ${clerkUserId}`);
            
            // Check if user exists by clerkUserId with timeout protection
            let user;
            try {
                user = await Promise.race([
                    prisma.user.findUnique({
                        where: { clerkUserId },
                    }),
                    new Promise((_, reject) =>
                        setTimeout(() => reject(new Error('Database query timeout')), 3000) // ✅ Reduced from 10000ms to 3000ms to fail fast
                    )
                ]) as any;
            } catch (dbError: any) {
                logger.error(`[findOrCreateUser] ❌ Database query failed:`, {
                    error: dbError.message,
                    code: dbError.code,
                    clerkUserId,
                });
                throw new Error(`Database connection failed: ${dbError.message}`);
            }

            if (user) {
                logger.info(`[findOrCreateUser] ✅ User found: ${user.username} (${user.id})`);
                this.updateLoginStreak(user.id).catch(err => 
                    logger.warn(`[findOrCreateUser] ⚠️ Failed to update login streak:`, err)
                );
                const refreshed = await this.refreshAutoProfileFromClerk(user, clerkUserId);
                return refreshed ?? user;
            }

            logger.info(`[findOrCreateUser] � User not found, fetching from Clerk...`);

            // ✅ Check Clerk cache first
            let clerkUser;
            
            try {
                clerkUser = await fetchClerkUserCached(clerkUserId);
                logger.info(`[findOrCreateUser] ✅ Clerk user fetched: ${clerkUser.id}`);
            } catch (clerkError: any) {
                logger.error(`[findOrCreateUser] ❌ Failed to fetch from Clerk after retries:`, clerkError);
                logger.warn(`[findOrCreateUser] ⚠️ Creating user with minimal data (Clerk unavailable)`);
                return await this.createMinimalClerkUser(clerkUserId);
            }

            // Primary email: prefer Clerk's primary id, else first verified, else any address
            const addresses = clerkUser.emailAddresses || [];
            let primaryEmail = addresses.find(
                (email: any) => email.id === clerkUser.primaryEmailAddressId
            );
            if (!primaryEmail) {
                primaryEmail = addresses.find(
                    (e: any) => e.verification?.status === 'verified'
                );
            }
            if (!primaryEmail && addresses.length > 0) {
                primaryEmail = addresses[0];
            }

            if (!primaryEmail) {
                logger.warn(
                    `[findOrCreateUser] ⚠️ No email addresses on Clerk user ${clerkUserId}; using minimal profile`
                );
                return await this.createMinimalClerkUser(clerkUserId);
            }

            logger.info(`[findOrCreateUser] 📧 Primary email: ${primaryEmail.emailAddress}`);

            const shortId = clerkUserId.replace('user_', '').slice(-8);
            const rawAddr = (primaryEmail.emailAddress || '').trim();
            const at = rawAddr.indexOf('@');
            const localPart =
                at > 0 ? rawAddr.slice(0, at) : rawAddr || 'user';
            const domain =
                at > 0 && at < rawAddr.length - 1
                    ? rawAddr.slice(at + 1)
                    : 'placeholder.invalid';
            const finalEmail = `${localPart}+${shortId}@${domain}`;

            logger.info(`[findOrCreateUser] 📧 Using email: ${finalEmail}`);

            const isOAuth = isClerkOAuthUser(clerkUser);
            const username = await generateUsername({
                email: primaryEmail.emailAddress,
                firstName: clerkUser.firstName,
                lastName: clerkUser.lastName,
                isOAuth,
            });

            const displayName =
                buildDisplayNameFromClerk(clerkUser, primaryEmail.emailAddress) || username;

            logger.info(`[findOrCreateUser] 👤 Using username: ${username}, displayName: ${displayName}`);

            // Create new user with timeout
            try {
                user = await Promise.race([
                    prisma.user.create({
                        data: {
                            clerkUserId,
                            email: finalEmail,
                            username,
                            displayName,
                            avatar: clerkUser.imageUrl || undefined,
                            emailVerified: clerkUser.emailAddresses[0]?.verification?.status === 'verified',
                            coins: 50,
                            level: 1,
                            xp: 0,
                        },
                    }),
                    new Promise((_, reject) =>
                        setTimeout(() => reject(new Error('Database create timeout')), 3000) // ✅ Reduced from 10000ms
                    )
                ]) as any;

                logger.info(`[findOrCreateUser] ✅ User created: ${user.username} (${user.id})`);
            } catch (createError: any) {
                logger.error(`[findOrCreateUser] ❌ Failed to create user:`, {
                    error: createError.message,
                    code: createError.code,
                    clerkUserId,
                });
                
                // ✅ If unique constraint fails, try to find existing user
                if (createError.code === 'P2002') {
                    logger.warn(`[findOrCreateUser] ⚠️ User already exists, fetching...`);
                    try {
                        user = await Promise.race([
                            prisma.user.findUnique({
                                where: { clerkUserId },
                            }),
                            new Promise((_, reject) =>
                                setTimeout(() => reject(new Error('Database query timeout')), 3000) // ✅ Reduced from 10000ms
                            )
                        ]) as any;
                        if (user) return user;
                    } catch (findError: any) {
                        logger.error(`[findOrCreateUser] ❌ Failed to find existing user:`, findError);
                        throw new Error(`Database connection failed: ${findError.message}`);
                    }
                }
                
                throw new Error(`Failed to create user in database: ${createError.message}`);
            }
            
            // Update login streak for new user (non-blocking)
            this.updateLoginStreak(user.id).catch(err => 
                logger.warn(`[findOrCreateUser] ⚠️ Failed to update login streak:`, err)
            );
            
            return user;
        } catch (error: any) {
            logger.error('[findOrCreateUser] ❌ Unexpected error:', error);
            logger.error('[findOrCreateUser] Error stack:', error.stack);
            throw error;
        }
    }

    /**
     * Update user login streak
     * Calculates consecutive login days based on lastLoginDate
     */
    private static async updateLoginStreak(userId: string): Promise<void> {
        try {
            const user = await prisma.user.findUnique({
                where: { id: userId },
                select: { settings: true },
            });
            const settings = (user?.settings ?? {}) as Record<string, unknown>;
            const tz = typeof settings.timezone === 'string'
                ? sanitizeTimezone(settings.timezone)
                : 'UTC';
            await awardDailyLogin(userId, tz);
            logger.info(`Updated login streak + XP for user ${userId}`);
        } catch (error) {
            logger.error('Error updating login streak:', error);
            // Don't throw - login streak update shouldn't fail the login
        }
    }

    /**
     * Get user by Clerk ID
     */
    static async getUserByClerkId(clerkUserId: string) {
        return await prisma.user.findUnique({
            where: { clerkUserId },
            select: {
                id: true,
                clerkUserId: true,
                email: true,
                username: true,
                displayName: true,
                avatar: true,
                bio: true,
                coins: true,
                level: true,
                xp: true,
                isVerified: true,
                isDeveloper: true,
                favoriteTeam: true,
                // FIFA Card fields
                position: true,
                countryFlag: true,
                age: true,
                height: true,
                weight: true,
                preferredFoot: true,
                lastUsernameChange: true,
                // Cover image
                coverImage: true,
                createdAt: true,
                updatedAt: true,
            },
        });
    }

    /**
     * Update user profile
     */
    static async updateUser(clerkUserId: string, data: {
        username?: string;
        displayName?: string;
        bio?: string;
        avatar?: string;
        favoriteTeam?: string;
    }) {
        // First check if user exists
        let user = await prisma.user.findUnique({
            where: { clerkUserId },
        });

        // If user doesn't exist, create them first
        if (!user) {
            logger.info('⚠️ User not found, creating first...');
            user = await this.findOrCreateUser(clerkUserId);
        }

        // Ensure user exists after findOrCreateUser
        if (!user) {
            throw new Error('Failed to find or create user');
        }

        // Check if username is being changed
        if (data.username && data.username !== user.username) {
            // Check 15 days cooldown
            if (user.lastUsernameChange) {
                const daysSinceLastChange = Math.floor(
                    (Date.now() - new Date(user.lastUsernameChange).getTime()) / (1000 * 60 * 60 * 24)
                );
                if (daysSinceLastChange < 15) {
                    const daysRemaining = 15 - daysSinceLastChange;
                    throw new Error(`You can change your username in ${daysRemaining} days`);
                }
            }

            // Check if username is unique
            const existingUser = await prisma.user.findUnique({
                where: { username: data.username },
            });
            if (existingUser && existingUser.id !== user.id) {
                throw new Error('Username already taken');
            }

            // Add lastUsernameChange to the update data
            (data as any).lastUsernameChange = new Date();
        }

        // Now update the user
        return await prisma.user.update({
            where: { clerkUserId },
            data,
        });
    }

    /**
     * Sync user data from Clerk
     * Useful for webhooks or manual sync
     */
    static async syncUserFromClerk(clerkUserId: string) {
        try {
            const clerkUser = await clerkClient.users.getUser(clerkUserId);
            
            const primaryEmail = clerkUser.emailAddresses.find(
                (email) => email.id === clerkUser.primaryEmailAddressId
            );

            if (!primaryEmail) {
                throw new Error('No email found for user');
            }

            // Fetch existing first to check its current fields
            const existingUser = await prisma.user.findUnique({
                where: { clerkUserId }
            });

            const updateData: any = {
                email: primaryEmail.emailAddress,
                emailVerified: clerkUser.emailAddresses[0]?.verification?.status === 'verified',
            };

            if (existingUser) {
                const clerkName = buildDisplayNameFromClerk(clerkUser, primaryEmail.emailAddress);
                const shouldRefreshDisplayName =
                    clerkName.length > 0 && isAutoGeneratedProfile(existingUser);

                if (shouldRefreshDisplayName) {
                    updateData.displayName = clerkName;
                }
                // Protect custom avatar
                if (!existingUser.avatar || existingUser.avatar.includes('clerk.com')) {
                    updateData.avatar = clerkUser.imageUrl || undefined;
                }
            } else {
                updateData.displayName =
                    buildDisplayNameFromClerk(clerkUser, primaryEmail.emailAddress) || undefined;
                updateData.avatar = clerkUser.imageUrl || undefined;
            }

            const user = await prisma.user.upsert({
                where: { clerkUserId },
                update: updateData,
                create: {
                    clerkUserId,
                    email: primaryEmail.emailAddress,
                    username: clerkUser.username || primaryEmail.emailAddress.split('@')[0],
                    displayName:
                        buildDisplayNameFromClerk(clerkUser, primaryEmail.emailAddress) ||
                        primaryEmail.emailAddress.split('@')[0],
                    avatar: clerkUser.imageUrl || undefined,
                    emailVerified: clerkUser.emailAddresses[0]?.verification?.status === 'verified',
                    coins: 50,
                    level: 1,
                },
            });

            return user;
        } catch (error) {
            logger.error('Error syncing user from Clerk:', error);
            throw error;
        }
    }

    /**
     * Delete user (for Clerk webhooks)
     */
    static async deleteUser(clerkUserId: string) {
        return await prisma.user.delete({
            where: { clerkUserId },
        });
    }
}
