export const LEAGUES = {
  WORLD_CUP: 1,
  CHAMPIONS_LEAGUE: 2,
  EUROPA_LEAGUE: 3,
  AFCON: 6,

  CAF_CHAMPIONS_LEAGUE: 12,
  CAF_CONFED_CUP: 13,

  PREMIER_LEAGUE: 39,
  LIGUE_1: 61,
  BUNDESLIGA: 78,
  SERIE_A: 135,
  LA_LIGA: 140,

  MOROCCAN_BOTOLA: 200,
  EGYPTIAN_PREMIER_LEAGUE: 233,
  SAUDI_PRO_LEAGUE: 307,
} as const;

export type LeagueId = (typeof LEAGUES)[keyof typeof LEAGUES];

export const MAJOR_LEAGUES: readonly LeagueId[] = [
  LEAGUES.PREMIER_LEAGUE,
  LEAGUES.LA_LIGA,
  LEAGUES.BUNDESLIGA,
  LEAGUES.SERIE_A,
  LEAGUES.LIGUE_1,

  LEAGUES.CHAMPIONS_LEAGUE,
  LEAGUES.EUROPA_LEAGUE,
  LEAGUES.WORLD_CUP,

  LEAGUES.SAUDI_PRO_LEAGUE,
  LEAGUES.EGYPTIAN_PREMIER_LEAGUE,
  LEAGUES.MOROCCAN_BOTOLA,

  LEAGUES.CAF_CHAMPIONS_LEAGUE,
  LEAGUES.CAF_CONFED_CUP,
  LEAGUES.AFCON,
] as const;

export const MAJOR_LEAGUE_SET = new Set<number>(MAJOR_LEAGUES);