export function isAutoGeneratedUsername(value?: string | null): boolean {
  return /^user_[a-z0-9]+$/i.test((value || '').trim());
}

export function isAutoGeneratedDisplayName(
  displayName?: string | null,
  username?: string | null,
): boolean {
  const name = (displayName || '').trim();
  if (!name) return true;
  if (username && name === username) return true;
  return isAutoGeneratedUsername(name);
}

/** Human-friendly name for rankings, pitch, etc. — never returns user_* handles. */
export function resolvePublicDisplayName(
  displayName?: string | null,
  username?: string | null,
  email?: string | null,
): string {
  const apiName = (displayName || '').trim();
  if (apiName && !isAutoGeneratedDisplayName(apiName, username)) {
    return apiName;
  }

  const uname = (username || '').trim();
  if (uname && !isAutoGeneratedUsername(uname)) {
    return uname;
  }

  const emailLocal =
    email
      ?.split('@')[0]
      ?.replace(/[._-]+/g, ' ')
      .trim() || '';
  if (emailLocal && !isAutoGeneratedUsername(emailLocal)) {
    return emailLocal;
  }

  return '';
}

export function resolvePublicFirstName(
  displayName?: string | null,
  username?: string | null,
  email?: string | null,
): string {
  const full = resolvePublicDisplayName(displayName, username, email);
  if (!full) return '';
  return full.split(/\s+/)[0] || full;
}
