export const PROFILE_STADIUM_COVER = require('../../assets/images/profile-v2/stadium-cover.jpg');
export const PROFILE_BIO_BALL = require('../../assets/images/profile-v2/bio-ball.jpg');

export const PROFILE_ICONS = {
  shield: require('../../assets/images/profile-v2/icon-shield.png'),
  fire: require('../../assets/images/profile-v2/icon-fire.png'),
  bullseye: require('../../assets/images/profile-v2/icon-bullseye.png'),
  trophy: require('../../assets/images/profile-v2/icon-trophy.png'),
  whatsapp: require('../../assets/images/profile-v2/icon-whatsapp.png'),
  instagram: require('../../assets/images/profile-v2/icon-instagram.png'),
  tiktok: require('../../assets/images/profile-v2/icon-tiktok.png'),
  facebook: require('../../assets/images/share-win/social-facebook.svg'),
  snapchat: require('../../assets/images/share-win/social-snapchat.svg'),
  x: require('../../assets/images/profile-v2/icon-x.svg'),
  youtube: require('../../assets/images/profile-v2/icon-youtube.svg'),
  linkedin: require('../../assets/images/profile-v2/icon-linkedin.svg'),
  email: require('../../assets/images/profile-v2/icon-email.png'),
  energy: require('../../assets/images/profile-v2/icon-energy.png'),
  energyLine: require('../../assets/images/profile-v2/energy-line.svg'),
  close: require('../../assets/images/profile-v2/icon-close.svg'),
  link: require('../../assets/images/profile-v2/icon-link.svg'),
  copy: require('../../assets/images/profile-v2/icon-copy.svg'),
  heart: require('../../assets/images/profile-v2/icon-heart.png'),
  video: require('../../assets/images/profile-v2/icon-video.png'),
  followers: require('../../assets/images/profile-v2/icon-followers.png'),
  following: require('../../assets/images/profile-v2/icon-following.png'),
  tabTrophy: require('../../assets/images/profile-v2/tab-trophy.svg'),
  tabTrophyActive: require('../../assets/images/profile-v2/tab-trophy-active.svg'),
  tabBullseye: require('../../assets/images/profile-v2/tab-bullseye.svg'),
  tabBullseyeActive: require('../../assets/images/profile-v2/tab-bullseye-active.svg'),
  tabVideo: require('../../assets/images/profile-v2/tab-video-inactive.svg'),
  tabVideoActive: require('../../assets/images/profile-v2/tab-video.svg'),
  lineChart: require('../../assets/images/profile-v2/icon-line-chart.svg'),
  predictionDivider: require('../../assets/images/profile-v2/prediction-divider.svg'),
  chevronDownPurple: require('../../assets/images/profile-v2/icon-chevron-down-purple.svg'),
} as const;
