import { StyleSheet } from 'react-native';
import { GROUP_COLORS } from './colors';

export const groupsHomeStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: GROUP_COLORS.bg },
  centered: { justifyContent: 'center', alignItems: 'center' },
  rowReverse: { flexDirection: 'row-reverse' },
  rtlText: { textAlign: 'right', writingDirection: 'rtl' },
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginBottom: 18 },
  xpChip: { minWidth: 84, borderRadius: 18, borderWidth: 1, borderColor: 'rgba(245,158,11,0.4)', backgroundColor: 'rgba(245,158,11,0.12)', paddingHorizontal: 12, paddingVertical: 7 },
  xpChipText: { color: '#F8D06A', fontWeight: '800', fontSize: 12, textAlign: 'center' },
  titleWrap: { flex: 1, alignItems: 'center' },
  title: { color: '#fff', fontWeight: '900', fontSize: 22 },
  subtitle: { color: GROUP_COLORS.textDim, fontSize: 12, marginTop: 2 },
  backBtn: { width: 34, height: 34, borderRadius: 17, borderWidth: 1, borderColor: GROUP_COLORS.border, alignItems: 'center', justifyContent: 'center', backgroundColor: GROUP_COLORS.white04 },
  heroCard: { alignItems: 'center', paddingVertical: 22, marginBottom: 28 },
  heroIcon: {
    width: 92,
    height: 92,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#5B3AA3',
    backgroundColor: '#28164A',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#7E3AF2',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    overflow: 'visible',
    shadowOffset: { width: 0, height: 0 },
  },
  heroIconWrapper: { position: 'relative' },
  heroBadge: {
    position: 'absolute',
    left: -10,
    top: -10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F5A623',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 5,
  },
  heroText: { marginTop: 16, color: '#73708C', fontSize: 14, fontWeight: '600', textAlign: 'center', lineHeight: 22, maxWidth: 280 },
  actionCard: { borderRadius: 20, borderWidth: 1, paddingHorizontal: 18, paddingVertical: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  createCard: { backgroundColor: '#34135A', borderColor: '#9963F3' },
  joinCard: { backgroundColor: '#2C170E', borderColor: 'rgba(245,158,11,0.45)' },
  actionTitle: { color: '#fff', fontWeight: '900', fontSize: 22 },
  actionSub: { color: GROUP_COLORS.textDim, fontSize: 13, marginTop: 4 },
  actionIcon: { width: 46, height: 46, borderRadius: 16, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.14)', backgroundColor: GROUP_COLORS.white04 },
  statsRow: { flexDirection: 'row', gap: 10, marginBottom: 14 },
  statCard: { flex: 1, minHeight: 110, backgroundColor: GROUP_COLORS.surface, borderRadius: 18, borderWidth: 1, borderColor: GROUP_COLORS.border, justifyContent: 'center', alignItems: 'center', gap: 5, paddingHorizontal: 8 },
  statCardHighlighted: { borderColor: GROUP_COLORS.accentAmber, backgroundColor: 'rgba(245,158,11,0.08)' },
  statValue: { color: GROUP_COLORS.successMint, fontWeight: '900', fontSize: 24 },
  statLabel: { color: GROUP_COLORS.textDim, fontSize: 11, textAlign: 'center' },
  sectionWrap: { marginTop: 6 },
  sectionTitle: { color: '#fff', fontWeight: '900', fontSize: 22, marginBottom: 10 },
  keyboardAvoidWrap: { width: '100%', justifyContent: 'flex-end' },
  groupCard: { backgroundColor: GROUP_COLORS.surface, borderWidth: 1, borderColor: GROUP_COLORS.border, borderRadius: 18, padding: 14, marginBottom: 10 },
  groupCardRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  groupAvatar: { width: 42, height: 42, borderRadius: 14, backgroundColor: 'rgba(168,85,247,0.18)', alignItems: 'center', justifyContent: 'center' },
  groupName: { color: '#fff', fontWeight: '900', fontSize: 18 },
  groupSub: { color: GROUP_COLORS.textDim, fontSize: 12, marginTop: 3 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.58)', justifyContent: 'flex-end', paddingHorizontal: 10, paddingBottom: 22 },
  sheetCard: { backgroundColor: '#130A27', borderWidth: 1, borderColor: GROUP_COLORS.border, borderRadius: 28, paddingTop: 12, paddingHorizontal: 18, paddingBottom: 24, marginBottom: 8 },
  sheetHandle: { alignSelf: 'center', width: 44, height: 5, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.3)', marginBottom: 18 },
  closeBtn: { position: 'absolute', top: 14, right: 16, width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: GROUP_COLORS.white06, borderWidth: 1, borderColor: GROUP_COLORS.white08 },
  closeBtnText: { color: '#CFC8E4', fontSize: 22, lineHeight: 24 },
  sheetTitle: { color: '#fff', fontWeight: '900', fontSize: 28, marginBottom: 18, textAlign: 'center' },
  imageUploadBox: { width: 96, height: 96, borderRadius: 22, borderWidth: 1, borderStyle: 'dashed', borderColor: 'rgba(168,85,247,0.6)', alignSelf: 'center', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: 'rgba(124,58,237,0.12)', marginBottom: 18 },
  imageUploadText: { color: GROUP_COLORS.accentSoft, fontWeight: '700', fontSize: 12 },
  fieldLabel: { color: '#D8D1E7', fontWeight: '700', fontSize: 15, marginBottom: 8 },
  sheetInput: { backgroundColor: '#261042', borderRadius: 18, borderWidth: 1, borderColor: 'rgba(168,85,247,0.24)', color: '#fff', paddingHorizontal: 16, paddingVertical: 14, marginBottom: 12, fontSize: 16 },
  visibilityRow: { flexDirection: 'row', gap: 8, marginBottom: 14 },
  visibilityChip: { flex: 1, borderRadius: 14, borderWidth: 1, borderColor: 'rgba(168,85,247,0.24)', paddingVertical: 12, alignItems: 'center', backgroundColor: GROUP_COLORS.white03 },
  visibilityChipActive: { backgroundColor: 'rgba(168,85,247,0.24)', borderColor: GROUP_COLORS.borderStrong },
  visibilityText: { color: '#fff', fontWeight: '800' },
  visibilityTextActive: { color: '#E8D5FF' },
  submitBtn: { borderRadius: 18, backgroundColor: GROUP_COLORS.accent, paddingVertical: 16, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  submitBtnDisabled: { opacity: 0.6 },
  submitBtnText: { color: '#fff', fontWeight: '900', fontSize: 20 },
});
