import { StyleSheet } from 'react-native';
import { GROUP_COLORS } from './colors';

export const groupViewStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: GROUP_COLORS.bg },
  centered: { justifyContent: 'center', alignItems: 'center' },
  rowReverse: { flexDirection: 'row-reverse' },
  rtlText: { textAlign: 'right', writingDirection: 'rtl' },
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginBottom: 18 },
  xpChip: { minWidth: 84, borderRadius: 18, borderWidth: 1, borderColor: 'rgba(245,158,11,0.4)', backgroundColor: 'rgba(245,158,11,0.12)', paddingHorizontal: 12, paddingVertical: 7 },
  xpChipText: { color: '#F8D06A', fontWeight: '800', fontSize: 12, textAlign: 'center' },
  titleWrap: { flex: 1, alignItems: 'center' },
  title: { color: '#fff', fontWeight: '900', fontSize: 22 },
  subtitle: { color: GROUP_COLORS.textDim, fontSize: 12, marginTop: 2 },
  backBtn: { width: 34, height: 34, borderRadius: 17, borderWidth: 1, borderColor: GROUP_COLORS.border, alignItems: 'center', justifyContent: 'center', backgroundColor: GROUP_COLORS.white04 },
  heroCard: { backgroundColor: GROUP_COLORS.surface, borderWidth: 1, borderColor: GROUP_COLORS.border, padding: 16, borderRadius: 22, marginBottom: 14 },
  heroAvatarWrap: { position: 'relative', width: 64, height: 64 },
  heroAvatar: {
    width: '100%',
    height: '100%',
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#341B62',
    borderWidth: 1,
    borderColor: '#5C34A5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroBadge: {
    position: 'absolute',
    right: -1,
    bottom: -1,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F59E0B',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: GROUP_COLORS.surface,
    zIndex: 10,
    elevation: 10,
  },
  heroTitle: { fontSize: 22, fontWeight: '900', color: '#fff' },
  heroSub: { fontSize: 12, color: '#8F8AA8', marginTop: 2 },
  heroTopCentered: { alignItems: 'center', justifyContent: 'center', marginBottom: 18 },
  heroButtonsRow: { flexDirection: 'row', gap: 10, marginTop: 4 },
  primaryButton: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: GROUP_COLORS.accent,
  },
  primaryButtonText: { color: '#fff', fontWeight: '800', fontSize: 14 },
  secondaryButton: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(116,48,201,0.22)',
    borderWidth: 1,
    borderColor: 'rgba(168,85,247,0.25)',
  },
  secondaryButtonText: { color: '#D8B4FE', fontWeight: '800', fontSize: 14 },
  codeCard: { backgroundColor: GROUP_COLORS.surface, borderRadius: 18, borderWidth: 1, borderColor: GROUP_COLORS.border, padding: 14, marginBottom: 14 },
  codeLabel: { color: GROUP_COLORS.textDim, fontSize: 12, marginBottom: 10 },
  codeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  codeValue: { color: '#fff', fontWeight: '900', fontSize: 28, letterSpacing: 2 },
  copyChip: { flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 14, borderWidth: 1, borderColor: 'rgba(168,85,247,0.24)', backgroundColor: GROUP_COLORS.white03, paddingHorizontal: 12, paddingVertical: 10 },
  copyChipText: { color: '#D8B4FE', fontWeight: '800' },
  sectionTitle: { color: '#fff', fontWeight: '900', fontSize: 22, marginBottom: 10 },
  infoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 16 },
  infoCard: { width: '48.3%', backgroundColor: GROUP_COLORS.surface, borderWidth: 1, borderColor: GROUP_COLORS.border, borderRadius: 18, padding: 14, minHeight: 106, justifyContent: 'space-between' },
  infoLabel: { color: GROUP_COLORS.textDim, fontSize: 12, marginTop: 8 },
  infoValue: { color: '#fff', fontWeight: '900', fontSize: 28 },
  membersWrap: { gap: 10 },
  memberCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: GROUP_COLORS.surface, borderWidth: 1, borderColor: GROUP_COLORS.border, borderRadius: 18, padding: 14, marginBottom: 10 },
  memberAvatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#F59E0B', alignItems: 'center', justifyContent: 'center' },
  ownerAvatar: { backgroundColor: '#F97316' },
  memberAvatarText: { color: '#fff', fontWeight: '900', fontSize: 16 },
  memberNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  memberName: { color: '#fff', fontWeight: '900', fontSize: 18 },
  memberRole: { color: GROUP_COLORS.textDim, fontSize: 13, marginTop: 3 },
  podiumCard: { backgroundColor: GROUP_COLORS.surface, borderWidth: 1, borderColor: GROUP_COLORS.border, borderRadius: 24, padding: 16, marginBottom: 14 },
  podiumRow: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-around', marginTop: 6 },
  podiumItem: { alignItems: 'center', flex: 1 },
  podiumCircle: { width: 58, height: 58, borderRadius: 29, backgroundColor: '#D9D9E3', alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  podiumCirclePrimary: { backgroundColor: '#FFB703' },
  podiumText: { color: '#1E1138', fontWeight: '900', fontSize: 22 },
  podiumName: { color: '#fff', fontWeight: '800', marginBottom: 8, fontSize: 13 },
  podiumBase: { width: 52, borderTopLeftRadius: 14, borderTopRightRadius: 14, backgroundColor: '#F59E0B', alignItems: 'center', justifyContent: 'center' },
  podiumRank: { color: '#1f1203', fontWeight: '900', fontSize: 16 },
  tableHead: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 6, marginBottom: 8 },
  tableHeadText: { color: GROUP_COLORS.textDim, fontSize: 12, fontWeight: '700' },
  rankCard: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: GROUP_COLORS.surface, borderWidth: 1, borderColor: GROUP_COLORS.border, borderRadius: 18, padding: 14, marginBottom: 10 },
  rankBadge: { width: 30, height: 30, borderRadius: 15, backgroundColor: 'rgba(168,85,247,0.14)', alignItems: 'center', justifyContent: 'center' },
  rankBadgeText: { color: '#D8B4FE', fontWeight: '900' },
  rankName: { color: '#fff', fontWeight: '900', fontSize: 18 },
  rankSub: { color: GROUP_COLORS.textDim, fontSize: 12, marginTop: 2 },
  rankMetric: { color: '#D8D1E7', fontSize: 13, fontWeight: '700', width: 48, textAlign: 'center' },
  rankMetricStrong: { color: '#F8D06A', fontSize: 15, fontWeight: '900', width: 48, textAlign: 'center' },
  roundHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  roundLink: { color: '#D8B4FE', fontWeight: '800', fontSize: 13 },
  matchCard: { backgroundColor: GROUP_COLORS.surface, borderWidth: 1, borderColor: GROUP_COLORS.border, borderRadius: 20, padding: 14, marginBottom: 10 },
  matchTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  matchTime: { color: GROUP_COLORS.textDim, fontSize: 12 },
  matchPillsRow: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  pillPrimary: { backgroundColor: '#B75CFF', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 5 },
  pillPrimaryText: { color: '#fff', fontWeight: '800', fontSize: 11 },
  pillMuted: { backgroundColor: GROUP_COLORS.white08, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 5 },
  pillMutedText: { color: '#D8D1E7', fontWeight: '700', fontSize: 11 },
  teamsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 16 },
  teamBlock: { flex: 1, alignItems: 'center', gap: 8 },
  teamDotA: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#3B82F6' },
  teamDotB: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#F43F5E' },
  teamName: { color: '#fff', fontWeight: '900', fontSize: 18, textAlign: 'center' },
  scoreRow: { flexDirection: 'row', gap: 10, alignItems: 'center', marginHorizontal: 8 },
  scoreBall: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#2D164A', borderWidth: 1, borderColor: 'rgba(168,85,247,0.24)', alignItems: 'center', justifyContent: 'center' },
  scoreBallText: { color: '#D8B4FE', fontWeight: '900', fontSize: 18 },
  predFooter: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 12 },
  predFooterText: { color: '#CFC8E4', fontSize: 12 },
  bottomBar: { position: 'absolute', left: 0, right: 0, bottom: 0, alignItems: 'center' },
  bottomTabs: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#100B24', borderWidth: 1, borderColor: 'rgba(168,85,247,0.2)', borderRadius: 28, padding: 8, marginHorizontal: 18, width: '84%', justifyContent: 'space-between' },
  bottomTab: { flex: 1, minHeight: 44, borderRadius: 20, alignItems: 'center', justifyContent: 'center', gap: 4 },
  bottomTabActive: { backgroundColor: GROUP_COLORS.accent },
  bottomTabText: { color: '#A78BFA', fontWeight: '800', fontSize: 12 },
  bottomTabTextActive: { color: '#fff' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.58)', justifyContent: 'flex-end', paddingHorizontal: 10, paddingBottom: 10 },
  modalCard: { backgroundColor: '#130A27', borderWidth: 1, borderColor: GROUP_COLORS.border, borderRadius: 28, paddingTop: 12, paddingHorizontal: 18, paddingBottom: 24, minHeight: '58%' },
  sheetHandle: { alignSelf: 'center', width: 44, height: 5, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.3)', marginBottom: 18 },
  closeBtn: { position: 'absolute', top: 14, right: 16, width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: GROUP_COLORS.white06, borderWidth: 1, borderColor: GROUP_COLORS.white08 },
  closeBtnText: { color: '#CFC8E4', fontSize: 22, lineHeight: 24 },
  modalTitle: { color: '#fff', fontWeight: '900', fontSize: 28, marginBottom: 18, textAlign: 'center' },
  searchBox: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#261042', borderRadius: 18, borderWidth: 1, borderColor: 'rgba(168,85,247,0.24)', paddingHorizontal: 14, paddingVertical: 12 },
  searchInput: { flex: 1, color: '#fff', fontSize: 15 },
  emptyModalText: { color: GROUP_COLORS.textDim, fontSize: 14, textAlign: 'center', marginTop: 30 },
  friendRow: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: GROUP_COLORS.surface, borderWidth: 1, borderColor: GROUP_COLORS.border, borderRadius: 18, padding: 14, marginBottom: 10 },
  friendInviteBtn: { backgroundColor: GROUP_COLORS.accent, borderRadius: 16, paddingHorizontal: 16, paddingVertical: 10 },
  friendInviteText: { color: '#fff', fontWeight: '900' },
  friendName: { color: '#fff', fontWeight: '900', fontSize: 18 },
  friendSub: { color: GROUP_COLORS.textDim, fontSize: 12, marginTop: 2 },
  friendAvatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: GROUP_COLORS.accent, alignItems: 'center', justifyContent: 'center' },
  friendAvatarText: { color: '#fff', fontWeight: '900', fontSize: 16 },
});
